(deftheme imcolor "used privately")

(defun heading (m n)
  `(:height ,m :box (:line-width ,n :color ,(face-background 'default nil 'default))))

(let* ((fg-color "#000000")
       (bg-color "#fefee8"))
  (custom-theme-set-faces
   'imcolor
   `(default ((t (:background ,bg-color :foreground ,fg-color))))
   `(font-lock-builtin-face ((t (:foreground "#858585"))))
   `(font-lock-comment-face ((t (:foreground "#b2b2b2" :background ,bg-color :slant italic))))
   `(font-lock-constant-face ((t (:foreground "#115bff"))))
   `(font-lock-doc-face ((t (:foreground "#5faf5f"))))
   `(font-lock-doc-string-face ((t (:foreground "#c4a000"))))
   `(font-lock-function-name-face ((t (:foreground "#ff5f00"))))
   `(font-lock-type-face ((t (:foreground "#008700"))))
   `(font-lock-keyword-face ((t (:foreground "blue"))))
   `(font-lock-string-face ((t (:foreground "#5f87ff"))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground "#d7afff"))))
   `(font-lock-regexp-grouping-construct ((t (:foreground "#d787ff"))))
   `(font-lock-variable-name-face ((t (:foreground "magenta"))))
   `(error ((t (:foreground "#d70000" :bold t))))
   `(warning ((t (:foreground "orange" :bold t))))
   `(success ((t (:foreground "darkgreen" :bold t))))
   `(region ((t (:background "#87d7ff" :foreground "#121212"))))
   `(mode-line ((t (:box nil :background "#5fafd7" :foreground "#fff"))))
   `(mode-line-inactive ((t (:box nil :background "#dadada" :foreground "#9e9e9e"))))
   `(mode-line-buffer-id ((t (:box nil :foreground "#3a3a3a" :background nil :bold t))))
   `(minibuffer-prompt ((t (:foreground "blue" :bold t))))

   ;; ORG-MODE
   ;; `(org-level-1 ((t (:inherit outline-1 ,@(heading 1.25 2)))))
   ;; `(org-level-2 ((t (:inherit outline-2 ,@(heading 1.2 2)))))
   ;; `(org-level-3 ((t (:inherit outline-3 ,@(heading 1.1 3)))))
   ;; `(org-level-4 ((t (:inherit outline-4 ,@(heading 1.05 5)))))
   ;; `(org-level-5 ((t (:inherit outline-5))))
   `(org-special-keyword ((t (:foreground "white"))))
   `(org-block-begin-line ((t (:background "#e5e4d9" :foreground ,bg-color))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:background "#fdfff7" :foreground "#006400" :slant italic))))
   `(org-date ((t (:foreground "#bcbcbc" :underline t))))
   `(org-table ((t (:foreground "RoyalBlue"))))
   ))

(provide-theme 'imcolor)
